@token_user = RmZO1vDOtejAA2CP_MiLVeN0e__ksnOwCEkVC66Ufs4=

### Create Admin User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "123456",
  "role": "ADMIN"
}

### Create Token
POST http://localhost:8080/api/user/token
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

### Create Type
POST http://localhost:8080/api/type
Content-Type: application/json
Authorization: Bearer {{token_user}}

< ../../../../../../../docs/forms/example-form.json

### Create occurrence
POST http://localhost:8080/api/occurrence
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "usersId": 1,
  "endDate": "2031-12-31",
  "importance": "URGENT",
  "occurrenceType": 1 ,
  "occurrenceInfo": {
    "messagePT": "O sinistro foi registado com base nas informações fornecidas pelo participante. De acordo com os dados recolhidos, o evento ocorreu na data, hora e local indicados, envolvendo as entidades identificadas na participação. As circunstâncias descritas foram registadas para efeitos de análise e validação, incluindo os danos reportados, os intervenientes envolvidos e quaisquer observações adicionais relevantes. Esta informação será utilizada no processo de avaliação do sinistro e poderá ser complementada ou atualizada caso sejam disponibilizados novos elementos.",
    "messageEN": "The claim has been registered based on the information provided by the claimant. According to the collected data, the incident occurred on the specified date, time and location, involving the parties identified in the report. The described circumstances have been recorded for review and validation purposes, including the reported damages, the parties involved and any additional relevant observations. This information will be used during the claim assessment process and may be supplemented or updated if further details become available.",
    "messageES": "El siniestro ha sido registrado con base en la información proporcionada por el declarante. Según los datos recopilados, el incidente ocurrió en la fecha, hora y lugar indicados, involucrando a las partes identificadas en la declaración. Las circunstancias descritas han sido registradas para su análisis y validación, incluyendo los daños comunicados, las personas o entidades implicadas y cualquier observación adicional relevante. Esta información se utilizará durante el proceso de evaluación del siniestro y podrá complementarse o actualizarse en caso de que se disponga de nuevos datos."
  }
}

### SSE for first occurrence
POST http://localhost:8080/api/occurrence/1/listen
Content-Type: application/json

### SSE for list of occurrences
POST http://localhost:8080/api/occurrence/listen
Content-Type: application/json

### Create new occurrence
POST http://localhost:8080/api/occurrence
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "usersId": 1,
  "endDate": "2028-12-31",
  "importance": "NORMAL",
  "occurrenceType": { "type": "fire", "sub": { "a": 1 } },
  "occurrenceInfo": { "location": "Lisbon", "people": [1,2,3] }
}

### Delete newly created occurrence
DELETE http://localhost:8080/api/occurrence/2
Content-Type: application/json

### Create intervenor
POST http://localhost:8080/api/intervenor
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "idNumber": "123456789",
  "idType": "NIF",
  "name": "Teste",
  "contactInfo": "912345678",
  "address": "Rua Teste, 123"
}

### SSE for first intervenor
POST http://localhost:8080/api/intervenor/1/listen
Content-Type: application/json

### SSE for list of intervenors
POST http://localhost:8080/api/intervenor/listen
Content-Type: application/json

### Create new intervenor
POST http://localhost:8080/api/intervenor
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "idNumber": "1452369873",
  "idType": "NIFSD",
  "name": "Teste",
  "contactInfo": "9263587145",
  "address": "Rua Teste, 123"
}

### Delete newly created intervenor
DELETE http://localhost:8080/api/intervenor/delete/byIdNumber/145236987
Content-Type: application/json

### Add intervenor to occurrence
POST http://localhost:8080/api/occurrence/1/intervenors
Content-Type: application/json

{
  "intervenorId": 1
}

### Remove intervenor from occurrence
DELETE http://localhost:8080/api/occurrence/1/intervenors
Content-Type: application/json

{
  "intervenorId": 1
}

### Update Intervenor
POST http://localhost:8080/api/intervenor/update/1
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
    "name": "Teste Atualizado"
}

### Create Evidence
POST http://localhost:8080/api/evidence
Authorization: Bearer {{token_user}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="Evidencia1.png"
Content-Type: image/png

< C:\Users\josec\Downloads\Evidencia1.png
--boundary123
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "type": { "category": "photo", "severity": "high" },
  "location": "Lisbon",
  "description": "Fire evidence image",
  "reporterId": 1,
  "occurrenceId": 1
}
--boundary123--

### SSE for Evidence
GET http://localhost:8080/api/evidence/1/listen
Authorization: Bearer {{token_user}}

### Delete Evidence
DELETE http://localhost:8080/api/evidence/1
Authorization: Bearer {{token_user}}

### Create Report
POST http://localhost:8080/api/report
Authorization: Bearer {{token_user}}
Content-Type: application/json

{
  "creatorId": 1,
  "title": "Fire Report",
  "description": "Detailed report of the fire incident.",
  "occurrenceId": 1,
  "addons": {
    "photos": [1],
    "documents": [1]
  },
  "language": "pt"
}

### SSE for Report
GET http://localhost:8080/api/report/1/listen
Authorization: Bearer {{token_user}}

###  Create User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "USER1",
  "email": "user1@gmail.com",
  "password": "user12"
}

### Add editor to report
POST http://localhost:8080/api/report/1/editors
Authorization: Bearer {{token_user}}
Content-Type: application/json

{
  "editorId": 2
}

### Remove editor from report
DELETE http://localhost:8080/api/report/1/editors/
Authorization: Bearer {{token_user}}
Content-Type: application/json

{
  "editorId": 2
}

### Update report status
POST http://localhost:8080/api/report/update-status/1
Authorization: Bearer {{token_user}}
Content-Type: application/json

{
  "newStatus": "SUBMITED"
}

### Delete Report
DELETE http://localhost:8080/api/report/3
Authorization: Bearer {{token_user}}

### Get overview Stats
GET http://localhost:8080/api/stats

### Get http protocol details
GET http://localhost:8080/api/debug/protocol
