@token_user = gMpURY2L-C8WKGqwOoCgCPHLYOUzLhftSes2j3AKdVc=

###  Create User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "USER1",
  "email": "user1@gmail.com",
  "password": "user12"
}

### Create Token
POST http://localhost:8080/api/user/token
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user12"
}

###Create occurrence
POST http://localhost:8080/api/occurrence
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "usersId": 2,
  "endDate": "2030-12-31",
  "importance": "NORMAL",
  "occurrenceType": { "type": "fire", "sub": { "a": 1 } },
  "occurrenceInfo": { "location": "Lisbon", "people": [1,2,3] }
}

### 6) List all occurrences
GET http://localhost:8080/api/occurrence

### 7) List occurrences by reporterId
GET http://localhost:8080/api/occurrence/reporter/2

### 8) Create intervenor
POST http://localhost:8080/api/intervenor
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "idNumber": "123456789",
  "idType": "NIF",
  "name": "Teste",
  "contactInfo": "912345678",
  "address": "Rua Teste, 123"
}

### Get all intervenors
GET http://localhost:8080/api/intervenor
